name: Generate JSON Schema

permissions:
  contents: write

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  run-generate-schema:
    # if: false # Uncomment to disable this job
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          repository: LivacoNew/CrabFetch
          ref: master
          path: CrabFetch

      # Setup Rust & Cargo's Cache
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: CrabFetch

      # Any deps we need, currently only libdbus-1
      - name: Install Dependencies
        run: |
          sudo apt -y update
          sudo apt -y install libdbus-1-dev

      # Actually run what we want to run
      - name: cargo clippy
        working-directory: CrabFetch
        run: cargo run --all-features -- -G > config.schema.json

      # Commit the changes
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add config.schema.json
          git commit -m "Update config.schema.json"
          git push
